name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'doc/**'
      - '**/*.md'
      - 'data/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'doc/**'
      - '**/*.md'
      - 'data/**'

jobs:
  lint:
    name: Lint & Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff bandit

      - name: Run ruff
        run: ruff check --ignore E402 .

      - name: Run bandit
        run: bandit -r app api structlog scripts -x tests,data

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        env:
          EMBEDDING_INDEX_BACKEND: memory
        run: pytest
